version: "3"

services:
  api:
    build: 
        context: ./node                         #que me construya utilizando dentro del contexto actual la carpeta node (hace build segun el Dockerfile que encuentre)
    ports:
    #  - "9001:3000"
      - "9001-9002:3000"                        #asigna un rango de puertos del servidor a los dockers (para escalar)
    #volumes:
    # - ./app:/usr/src                       #monta mi contexto de build en la carpeta src
    # - /usr/src/node_modules                 #como hay archivos que no deben modificarse, le especificas el nombre para que no los toque
#    networks: 
#      tnp_net:
#        aliases: 
#          - api
    deploy:
        replicas: 2                             #levanta 2 instancias. hay que ejecutar el docker-compose up --compatibility
  lb:
    build: 
        context: ./nginx                        #levanta el balanceador de carga
    ports:
      - "9000:80"
#    networks: 
#      tnp_net:
#        aliases: 
#          - lb
#networks:
#  tnp_net: