CREATE DATABASE IF NOT EXISTS tnpdemp;
CREATE USER 'tnproot'@'%' IDENTIFIED BY 'tnproot';
GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON `tnpdemo`.* TO 'tnproot'@'%';
FLUSH PRIVILEGES;